app:
	uvicorn app:app --host 0.0.0.0 --port 3000 --reload
mongo:
	uvicorn mongo:app --host 0.0.0.0 --port 3000 --reload
park:
	uvicorn park:app --host 0.0.0.0 --port 3000 --reload
park2:
	uvicorn park_test:app --host 0.0.0.0 --port 3000 --reload
park3:
	uvicorn park_test2:app --host 0.0.0.0 --port 3000 --reload

# JSON 서버 실행 명령어
install:
	npm install -g json-server